### ISSUE TITLE
服务端无法启动

### ISSUE THREAD

**Issue by pheotry** [NullpointerW/AniCat#11]
goroutine 1 [running]:
github.com/NullpointerW/anicat/errs.PanicErr(...)
	/root/AniCat/errs/error.go:58
github.com/NullpointerW/anicat/conf.init.0()
	/root/AniCat/conf/env.go:111 +0x506

**Comment by NullpointerW** [comment]
检查下配置文件路径是否正确

**Comment by Goojoe** [comment]
[logs.zip](https://github.com/user-attachments/files/17524425/logs.zip)
客户端无法启动,服务安装日志为`error: The service did not respond to the start or control request in a timely fashion.`
qbitEE版本5.0.0.10
配置文件
```
port: 12314 # 监听端口 docker-compose部署无需更改
path: F:\bangumi # 番剧下载路径 docker-compose部署无需更改
drop-duplicate: on # 若存在相同集数，则删除重复项（建议开启)
qbittorrent:
  url: http://localhost:8090 # qbt-api url,在docker-compose部署时无需更改
  username: admin
  password: adminadmin
  localed: yes # 如果qbt开启了本地登录选项，则可不用填写用户,名和密码，docker-compose部署则可忽视此项
  timeout: 3500 # qbt-api请求的超时时间，有时任务添加到qbt上，调用api后无法立即响应到数据

bangumi-log: on #开启番剧更新日志，将在根目录创建日志，记录剧集的更新信息

```

提个别的建议
好久没用这软件了，重新下又忘了下配置文件，而且只下载了服务端，忘了下载客户端。这两个完全（配置文件，windows启动服务管理）可以集成到程序里吧。
